### ISSUE TITLE
Bug: Navigation menu does not stay open on first click.

### ISSUE THREAD

**Issue by jackblackCH** [shadcn/ui#76]
The NavigationMenu does stay open on a first click and closes again. It works after a second click.
Can be reproduced by clickinng on a example on the docs page: https://ui.shadcn.com/docs/primitives/navigation-menu.

**Comment by lucaspessivaldo** [comment]
This is the same behavior of the radix Navigation Menu - https://www.radix-ui.com/docs/primitives/components/navigation-menu.
Because when you are with the mouse over the navigation opens and if you click it will close again, and the second click you open that again.

So, the mouse-over opens the navigation, and your first click closes that.

**Comment by jackblackCH** [comment]
Oh I see, thanks for mentioning, I will close this then as It's on radix' side.

Although to me this behavior is strange and kinda an anti pattern as it's confusing with pointer devices like a mouse, especially with hybrid devices with mouse and touch. It's a buggy behavior if you hover and click immediately - as it closes after a short flicker.

**Comment by mweel1** [comment]
This was messing with me also.

**Comment by kachkaev** [comment]
Upstream issue: https://github.com/radix-ui/primitives/issues/1630 (and https://github.com/radix-ui/primitives/issues/2326). Workaround: https://github.com/radix-ui/primitives/issues/1630#issuecomment-1545995075
